import { type Api } from "../2_tl.js";
import type { BusinessConnection, CallbackQuery, ChatAction, ChatMember, ChatP, ChatPChannel, ChatPGroup, ChatPSupergroup, ChosenInlineResult, FileSource, ID, InlineQuery, InlineQueryResult, InputMedia, InviteLink, Message, MessageAnimation, MessageAudio, MessageContact, MessageDice, MessageDocument, MessageInvoice, MessageLocation, MessagePhoto, MessagePoll, MessageSticker, MessageText, MessageVenue, MessageVideo, MessageVideoNote, MessageVoice, PriceTag, Reaction, Update, User } from "../3_types.js";
import type { AddReactionParams, AnswerCallbackQueryParams, AnswerInlineQueryParams, AnswerPreCheckoutQueryParams, BanChatMemberParams, CreateInviteLinkParams, DeleteMessagesParams, EditInlineMessageCaptionParams, EditInlineMessageMediaParams, EditInlineMessageTextParams, EditMessageCaptionParams, EditMessageLiveLocationParams, EditMessageMediaParams, EditMessageReplyMarkupParams, EditMessageTextParams, ForwardMessagesParams, GetChatMembersParams, GetCreatedInviteLinksParams, PinMessageParams, PromoteChatMemberParams, ReplyParams, SearchMessagesParams, SendAnimationParams, SendAudioParams, SendContactParams, SendDiceParams, SendDocumentParams, SendInvoiceParams, SendLocationParams, SendMediaGroupParams, SendMessageParams, SendPhotoParams, SendPollParams, SendStickerParams, SendVenueParams, SendVideoNoteParams, SendVideoParams, SendVoiceParams, SetChatMemberRightsParams, SetChatPhotoParams, SetReactionsParams } from "./0_params.js";
import type { ClientGeneric } from "./1_client_generic.js";
export declare class Context {
    #private;
    constructor(client: ClientGeneric, me: User | undefined, update: Update);
    get update(): Update;
    get me(): User | undefined;
    get client(): ClientGeneric;
    get msg(): Message | undefined;
    get message(): Message | undefined;
    get editedMessage(): Message | undefined;
    get callbackQuery(): CallbackQuery | undefined;
    get inlineQuery(): InlineQuery | undefined;
    get chosenInlineResult(): ChosenInlineResult | undefined;
    get chat(): ChatP | undefined;
    get from(): User | ChatPGroup | ChatPSupergroup | ChatPChannel | undefined;
    toJSON(): Update | {
        update: Api.Update;
    };
    reply(text: string, params?: Omit<SendMessageParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageText>;
    replyPoll(question: string, options: string[], params?: Omit<SendPollParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessagePoll>;
    replyPhoto(photo: FileSource, params?: Omit<SendPhotoParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessagePhoto>;
    replyMediaGroup(media: InputMedia[], params?: Omit<SendMediaGroupParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<Message[]>;
    replyInvoice(title: string, description: string, payload: string, currency: string, prices: PriceTag[], params?: Omit<SendInvoiceParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageInvoice>;
    replyDocument(document: FileSource, params?: Omit<SendDocumentParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageDocument>;
    replySticker(sticker: FileSource, params?: Omit<SendStickerParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageSticker>;
    replyLocation(latitude: number, longitude: number, params?: Omit<SendLocationParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageLocation>;
    replyDice(params?: Omit<SendDiceParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageDice>;
    replyVenue(latitude: number, longitude: number, title: string, address: string, params?: Omit<SendVenueParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageVenue>;
    replyContact(firstName: string, number: string, params?: Omit<SendContactParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageContact>;
    replyVideo(video: FileSource, params?: Omit<SendVideoParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageVideo>;
    replyAnimation(animation: FileSource, params?: Omit<SendAnimationParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageAnimation>;
    replyVoice(voice: FileSource, params?: Omit<SendVoiceParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageVoice>;
    replyAudio(audio: FileSource, params?: Omit<SendAudioParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageAudio>;
    replyVideoNote(videoNote: FileSource, params?: Omit<SendVideoNoteParams, "replyTo" | "businessConnectionId"> & ReplyParams): Promise<MessageVideoNote>;
    delete(): Promise<void>;
    forward(to: ID, params?: ForwardMessagesParams): Promise<Message>;
    pin(params?: PinMessageParams): Promise<void>;
    unpin(): Promise<void>;
    banSender(params?: BanChatMemberParams): Promise<void>;
    kickSender(): Promise<void>;
    setSenderRights(params?: SetChatMemberRightsParams): Promise<void>;
    getChatAdministrators(): Promise<ChatMember[]>;
    react(reactions: Reaction[], params?: SetReactionsParams): Promise<void>;
    sendChatAction(action: ChatAction, params?: {
        messageThreadId?: number;
    }): Promise<void>;
    editInlineMessageText(text: string, params?: EditInlineMessageTextParams): Promise<void>;
    editInlineMessageCaption(params?: EditInlineMessageCaptionParams): Promise<void>;
    editInlineMessageMedia(media: InputMedia, params?: EditInlineMessageMediaParams): Promise<void>;
    editInlineMessageLiveLocation(latitude: number, longitude: number, params?: EditMessageLiveLocationParams): Promise<void>;
    editInlineMessageReplyMarkup(params?: EditMessageReplyMarkupParams): Promise<void>;
    editMessageText(messageId: number, text: string, params?: EditMessageTextParams): Promise<MessageText>;
    editMessageCaption(messageId: number, params?: EditMessageCaptionParams): Promise<Message>;
    editMessageMedia(messageId: number, media: InputMedia, params?: EditMessageMediaParams): Promise<Message>;
    editMessageLiveLocation(messageId: number, latitude: number, longitude: number, params?: EditMessageLiveLocationParams): Promise<Message>;
    editMessageReplyMarkup(messageId: number, params?: EditMessageReplyMarkupParams): Promise<Message>;
    answerCallbackQuery(params?: AnswerCallbackQueryParams): Promise<void>;
    answerInlineQuery(results: InlineQueryResult[], params?: AnswerInlineQueryParams): Promise<void>;
    getMessage(messageId: number): Promise<Message | null>;
    getMessages(messageIds: number[]): Promise<Message[]>;
    forwardMessage(to: ID, messageId: number, params?: ForwardMessagesParams): Promise<Message>;
    forwardMessages(to: ID, messageIds: number[], params?: ForwardMessagesParams): Promise<Message[]>;
    deleteMessage(messageId: number, params?: DeleteMessagesParams): Promise<void>;
    deleteMessages(messageIds: number[], params?: DeleteMessagesParams): Promise<void>;
    pinMessage(messageId: number, params?: PinMessageParams): Promise<void>;
    unpinMessage(messageId: number): Promise<void>;
    unpinMessages(): Promise<void>;
    setAvailableReactions(availableReactions: "none" | "all" | Reaction[]): Promise<void>;
    addReaction(messageId: number, reaction: Reaction, params?: AddReactionParams): Promise<void>;
    removeReaction(messageId: number, reaction: Reaction): Promise<void>;
    setReactions(messageId: number, reactions: Reaction[], params?: SetReactionsParams): Promise<void>;
    read(): Promise<void>;
    setChatPhoto(photo: FileSource, params?: SetChatPhotoParams): Promise<void>;
    deletChatPhoto(): Promise<void>;
    banChatMember(memberId: ID, params?: BanChatMemberParams): Promise<void>;
    unbanChatMember(memberId: ID): Promise<void>;
    kickChatMember(memberId: ID): Promise<void>;
    setChatMemberRights(memberId: ID, params?: SetChatMemberRightsParams): Promise<void>;
    promoteChatMember(userId: ID, params?: PromoteChatMemberParams): Promise<void>;
    deleteChatMemberMessages(userId: ID): Promise<void>;
    searchMessages(params?: Omit<SearchMessagesParams, "chatId">): Promise<Message[]>;
    setBoostsRequiredToCircumventRestrictions(boosts: number): Promise<void>;
    createInviteLink(params?: CreateInviteLinkParams): Promise<InviteLink>;
    getCreatedInviteLinks(params?: GetCreatedInviteLinksParams): Promise<InviteLink[]>;
    leaveChat(): Promise<void>;
    blockUser(): Promise<void>;
    unblockUser(): Promise<void>;
    getChatMember(userId: ID): Promise<ChatMember>;
    getChatMembers(params?: GetChatMembersParams): Promise<ChatMember[]>;
    setChatStickerSet(setName: string): Promise<void>;
    deleteChatStickerSet(): Promise<void>;
    getBusinessConnection(): Promise<BusinessConnection>;
    answerPreCheckoutQuery(ok: boolean, params?: AnswerPreCheckoutQueryParams): Promise<void>;
    approveJoinRequest(): Promise<void>;
    declineJoinRequest(): Promise<void>;
}
//# sourceMappingURL=2_context.d.ts.map