import type { Api, Mtproto } from "../2_tl.js";
import type { DC } from "../3_transport.js";
import type { BotCommand, BotTokenCheckResult, BusinessConnection, CallbackQueryAnswer, CallbackQueryQuestion, Chat, ChatAction, ChatListItem, ChatMember, ChatP, ChatPChannel, ChatPGroup, ChatPSupergroup, ChatSettings, ClaimedGifts, CodeCheckResult, FailedInvitation, FileSource, Gift, ID, InactiveChat, InlineQueryAnswer, InlineQueryResult, InputMedia, InputStoryContent, InviteLink, JoinRequest, LinkPreview, LiveStreamChannel, Message, MessageAnimation, MessageAudio, MessageContact, MessageDice, MessageDocument, MessageInvoice, MessageLocation, MessagePhoto, MessagePoll, MessageReactionList, MessageSticker, MessageText, MessageVenue, MessageVideo, MessageVideoNote, MessageVoice, MiniAppInfo, NetworkStatistics, ParseMode, PasswordCheckResult, Poll, PriceTag, Reaction, SavedChats, SlowModeDuration, Sticker, StickerSet, Story, Topic, Translation, User, VideoChat, VideoChatActive, VideoChatScheduled, VoiceTranscription } from "../3_types.js";
import type { AddChatMemberParams, AddContactParams, AddReactionParams, AnswerCallbackQueryParams, AnswerInlineQueryParams, AnswerPreCheckoutQueryParams, ApproveJoinRequestsParams, BanChatMemberParams, CreateChannelParams, CreateGroupParams, CreateInviteLinkParams, CreateStoryParams, CreateSupergroupParams, CreateTopicParams, DeclineJoinRequestsParams, DeleteMessageParams, DeleteMessagesParams, DownloadLiveStreamSegmentParams, DownloadParams, EditInlineMessageCaptionParams, EditInlineMessageMediaParams, EditInlineMessageTextParams, EditMessageCaptionParams, EditMessageLiveLocationParams, EditMessageMediaParams, EditMessageReplyMarkupParams, EditMessageTextParams, EditTopicParams, ForwardMessagesParams, GetChatMembersParams, GetChatsParams, GetClaimedGiftsParams, GetCommonChatsParams, GetCreatedInviteLinksParams, GetHistoryParams, GetJoinRequestsParams, GetLinkPreviewParams, GetMessageReactionsParams, GetMyCommandsParams, GetSavedChatsParams, GetSavedMessagesParams, GetTranslationsParams, InvokeParams, JoinVideoChatParams, OpenChatParams, OpenMiniAppParams, PinMessageParams, PromoteChatMemberParams, ScheduleVideoChatParams, SearchMessagesParams, SendAnimationParams, SendAudioParams, SendContactParams, SendDiceParams, SendDocumentParams, SendGiftParams, SendInlineQueryParams, SendInvoiceParams, SendLocationParams, SendMediaGroupParams, SendMessageParams, SendPhotoParams, SendPollParams, SendStickerParams, SendVenueParams, SendVideoNoteParams, SendVideoParams, SendVoiceParams, SetBirthdayParams, SetChatMemberRightsParams, SetChatPhotoParams, SetEmojiStatusParams, SetLocationParams, SetMyCommandsParams, SetNameColorParams, SetPersonalChannelParams, SetProfileColorParams, SetReactionsParams, SetSignaturesEnabledParams, SignInParams, StartBotParams, StartVideoChatParams, StopPollParams, UnpinMessageParams, UpdateProfileParams } from "./0_params.js";
import type { WorkerRequest } from "./0_worker_request.js";
import type { ClientGeneric } from "./1_client_generic.js";
import { type InvokeErrorHandler } from "./1_invoke_middleware.js";
import type { WorkerResponse } from "./1_worker_response.js";
import type { Context } from "./2_context.js";
import { Composer } from "./4_composer.js";
export interface ClientDispatcherParams {
    storage?: "memory" | "indexeddb" | "denokv";
    apiId?: number;
    apiHash?: string;
    parseMode?: ParseMode;
    appVersion?: string;
    deviceModel?: string;
    language?: string;
    platform?: string;
    systemLangCode?: string;
    systemVersion?: string;
    defaultHandlers?: boolean;
    outgoingMessages?: boolean;
    guaranteeUpdateDelivery?: boolean;
    dropPendingUpdates?: boolean;
    persistCache?: boolean;
    disableUpdates?: boolean;
    authString?: string;
    initialDc?: DC;
}
export declare class ClientDispatcher<C extends Context = Context> extends Composer<C> implements ClientGeneric {
    #private;
    constructor(worker: Worker, id: string);
    handleResponse(response: WorkerResponse): Promise<void>;
    get id(): string;
    init(params?: ClientDispatcherParams): Promise<void>;
    connect(): Promise<void>;
    disconnect(): Promise<void>;
    start(params?: SignInParams): Promise<void>;
    handleInvokeError(request: WorkerRequest): Promise<boolean>;
    invoke: {
        <T extends Api.AnyFunction | Mtproto.ping, R = T extends Mtproto.ping ? Mtproto.pong : T extends Api.AnyGenericFunction<infer X> ? Api.ReturnType<X> : T["_"] extends keyof Api.Functions ? Api.ReturnType<T> extends never ? Api.ReturnType<Api.Functions[T["_"]]> : never : never>(function_: T, params?: InvokeParams): Promise<R>;
        use: (handler: InvokeErrorHandler<ClientDispatcher<C>>) => void;
    };
    sendCode(phoneNumber: string): Promise<void>;
    checkCode(code: string): Promise<CodeCheckResult>;
    getPasswordHint(): Promise<string | null>;
    checkPassword(password: string): Promise<PasswordCheckResult>;
    checkBotToken(botToken: string): Promise<BotTokenCheckResult>;
    signIn(params?: SignInParams): Promise<void>;
    signOut(): Promise<void>;
    exportAuthString(): Promise<string>;
    importAuthString(authString: string): Promise<void>;
    getInputPeer(id: ID): Promise<Api.InputPeer>;
    getInputChannel(id: ID): Promise<Api.inputChannel | Api.inputChannelFromMessage>;
    getInputUser(id: ID): Promise<Api.inputUserSelf | Api.inputUser | Api.inputUserFromMessage>;
    getMe(): Promise<User>;
    showUsername(id: ID, username: string): Promise<void>;
    hideUsername(id: ID, username: string): Promise<void>;
    reorderUsernames(id: ID, order: string[]): Promise<boolean>;
    hideUsernames(id: ID): Promise<boolean>;
    getBusinessConnection(id: string): Promise<BusinessConnection>;
    setOnline(online: boolean): Promise<void>;
    setEmojiStatus(id: string, params?: SetEmojiStatusParams): Promise<void>;
    setUserEmojiStatus(userId: ID, id: string, params?: SetEmojiStatusParams): Promise<void>;
    updateProfile(params?: UpdateProfileParams): Promise<void>;
    setBirthday(params?: SetBirthdayParams): Promise<void>;
    setPersonalChannel(params?: SetPersonalChannelParams): Promise<void>;
    setNameColor(color: number, params?: SetNameColorParams): Promise<void>;
    setProfileColor(color: number, params?: SetProfileColorParams): Promise<void>;
    setLocation(params?: SetLocationParams): Promise<void>;
    sendMessage(chatId: ID, text: string, params?: SendMessageParams): Promise<MessageText>;
    sendPhoto(chatId: ID, photo: FileSource, params?: SendPhotoParams): Promise<MessagePhoto>;
    sendDocument(chatId: ID, document: FileSource, params?: SendDocumentParams): Promise<MessageDocument>;
    sendSticker(chatId: ID, sticker: FileSource, params?: SendStickerParams): Promise<MessageSticker>;
    sendVideo(chatId: ID, video: FileSource, params?: SendVideoParams): Promise<MessageVideo>;
    sendAnimation(chatId: ID, animation: FileSource, params?: SendAnimationParams): Promise<MessageAnimation>;
    sendVoice(chatId: ID, voice: FileSource, params?: SendVoiceParams): Promise<MessageVoice>;
    sendAudio(chatId: ID, audio: FileSource, params?: SendAudioParams): Promise<MessageAudio>;
    sendMediaGroup(chatId: ID, media: InputMedia[], params?: SendMediaGroupParams): Promise<Message[]>;
    sendVideoNote(chatId: ID, videoNote: FileSource, params?: SendVideoNoteParams): Promise<MessageVideoNote>;
    sendLocation(chatId: ID, latitude: number, longitude: number, params?: SendLocationParams): Promise<MessageLocation>;
    sendContact(chatId: ID, firstName: string, number: string, params?: SendContactParams): Promise<MessageContact>;
    sendDice(chatId: ID, params?: SendDiceParams): Promise<MessageDice>;
    sendVenue(chatId: ID, latitude: number, longitude: number, title: string, address: string, params?: SendVenueParams): Promise<MessageVenue>;
    sendPoll(chatId: ID, question: string, options: string[], params?: SendPollParams): Promise<MessagePoll>;
    sendInvoice(chatId: ID, title: string, description: string, payload: string, currency: string, prices: PriceTag[], params?: SendInvoiceParams): Promise<MessageInvoice>;
    editMessageText(chatId: ID, messageId: number, text: string, params?: EditMessageTextParams): Promise<MessageText>;
    editMessageCaption(chatId: ID, messageId: number, params?: EditMessageCaptionParams): Promise<Message>;
    editMessageMedia(chatId: ID, messageId: number, media: InputMedia, params?: EditMessageMediaParams): Promise<Message>;
    editInlineMessageMedia(inlineMessageId: string, media: InputMedia, params?: EditInlineMessageMediaParams): Promise<void>;
    editInlineMessageText(inlineMessageId: string, text: string, params?: EditInlineMessageTextParams): Promise<void>;
    editInlineMessageCaption(inlineMessageId: string, params?: EditInlineMessageCaptionParams): Promise<void>;
    editMessageReplyMarkup(chatId: ID, messageId: number, params?: EditMessageReplyMarkupParams): Promise<Message>;
    editInlineMessageReplyMarkup(inlineMessageId: string, params?: EditMessageReplyMarkupParams): Promise<void>;
    editMessageLiveLocation(chatId: ID, messageId: number, latitude: number, longitude: number, params?: EditMessageLiveLocationParams): Promise<MessageLocation>;
    editInlineMessageLiveLocation(inlineMessageId: string, latitude: number, longitude: number, params?: EditMessageLiveLocationParams): Promise<void>;
    getMessages(chatId: ID, messageIds: number[]): Promise<Message[]>;
    getMessage(chatId: ID, messageId: number): Promise<Message | null>;
    resolveMessageLink(link: string): Promise<Message | null>;
    deleteMessages(chatId: ID, messageIds: number[], params?: DeleteMessagesParams): Promise<void>;
    deleteMessage(chatId: ID, messageId: number, params?: DeleteMessageParams): Promise<void>;
    deleteChatMemberMessages(chatId: ID, memberId: ID): Promise<void>;
    deleteScheduledMessages(chatId: ID, messageIds: number[]): Promise<void>;
    deleteScheduledMessage(chatId: ID, messageId: number): Promise<void>;
    sendScheduledMessages(chatId: ID, messageIds: number[]): Promise<Message[]>;
    sendScheduledMessage(chatId: ID, messageId: number): Promise<Message>;
    pinMessage(chatId: ID, messageId: number, params?: PinMessageParams): Promise<void>;
    unpinMessage(chatId: ID, messageId: number, params?: UnpinMessageParams): Promise<void>;
    unpinMessages(chatId: ID): Promise<void>;
    forwardMessages(from: ID, to: ID, messageIds: number[], params?: ForwardMessagesParams): Promise<Message[]>;
    forwardMessage(from: ID, to: ID, messageId: number, params?: ForwardMessagesParams): Promise<Message>;
    stopPoll(chatId: ID, messageId: number, params?: StopPollParams): Promise<Poll>;
    sendChatAction(chatId: ID, action: ChatAction, params?: {
        messageThreadId?: number;
    }): Promise<void>;
    searchMessages(params?: SearchMessagesParams): Promise<Message[]>;
    readMessages(chatId: ID, untilMessageId: number): Promise<void>;
    startBot(botId: number, params?: StartBotParams): Promise<Message>;
    transcribeVoice(chatId: ID, messageId: number): Promise<VoiceTranscription>;
    getStickerSet(name: string): Promise<StickerSet>;
    getLinkPreview(text: string, params?: GetLinkPreviewParams): Promise<LinkPreview | null>;
    openMiniApp(botId: ID, chatId: ID, params?: OpenMiniAppParams): Promise<MiniAppInfo>;
    getProgressId(): Promise<string>;
    getSavedMessages(chatId: ID, params?: GetSavedMessagesParams): Promise<Message[]>;
    getSavedChats(params?: GetSavedChatsParams): Promise<SavedChats>;
    getMessageReactions(chatId: ID, messageId: number, params?: GetMessageReactionsParams): Promise<MessageReactionList>;
    vote(chatId: ID, messageId: number, optionIndexes: number[]): Promise<void>;
    retractVote(chatId: ID, messageId: number): Promise<void>;
    downloadChunk(fileId: string, params?: DownloadParams): Promise<Uint8Array>;
    download(fileId: string, params?: DownloadParams): AsyncGenerator<Uint8Array, void, unknown>;
    getCustomEmojiStickers(id: string | string[]): Promise<Sticker[]>;
    getChats(params?: GetChatsParams): Promise<ChatListItem[]>;
    getChat(chatId: ID): Promise<Chat>;
    getHistory(chatId: ID, params?: GetHistoryParams): Promise<Message[]>;
    setAvailableReactions(chatId: ID, availableReactions: "none" | "all" | Reaction[]): Promise<void>;
    setChatPhoto(chatId: ID, photo: FileSource, params?: SetChatPhotoParams): Promise<void>;
    deleteChatPhoto(chatId: ID): Promise<void>;
    banChatMember(chatId: ID, memberId: ID, params?: BanChatMemberParams): Promise<void>;
    unbanChatMember(chatId: ID, memberId: ID): Promise<void>;
    kickChatMember(chatId: ID, memberId: ID): Promise<void>;
    setChatMemberRights(chatId: ID, memberId: ID, params?: SetChatMemberRightsParams): Promise<void>;
    getChatAdministrators(chatId: ID): Promise<ChatMember[]>;
    enableJoinRequests(chatId: ID): Promise<void>;
    disableJoinRequests(chatId: ID): Promise<void>;
    getInactiveChats(): Promise<InactiveChat[]>;
    getCreatedInviteLinks(chatId: ID, params?: GetCreatedInviteLinksParams): Promise<InviteLink[]>;
    joinChat(chatId: ID): Promise<void>;
    leaveChat(chatId: ID): Promise<void>;
    getChatMember(chatId: ID, userId: ID): Promise<ChatMember>;
    getChatMembers(chatId: ID, params?: GetChatMembersParams): Promise<ChatMember[]>;
    setChatStickerSet(chatId: ID, setName: string): Promise<void>;
    deleteChatStickerSet(chatId: ID): Promise<void>;
    setBoostsRequiredToCircumventRestrictions(chatId: ID, boosts: number): Promise<void>;
    createInviteLink(chatId: ID, params?: CreateInviteLinkParams): Promise<InviteLink>;
    approveJoinRequest(chatId: ID, userId: ID): Promise<void>;
    declineJoinRequest(chatId: ID, userId: ID): Promise<void>;
    approveJoinRequests(chatId: ID, params?: ApproveJoinRequestsParams): Promise<void>;
    declineJoinRequests(chatId: ID, params?: DeclineJoinRequestsParams): Promise<void>;
    getJoinRequests(chatId: ID, params?: GetJoinRequestsParams): Promise<JoinRequest[]>;
    addChatMember(chatId: ID, userId: ID, params?: AddChatMemberParams): Promise<FailedInvitation[]>;
    addChatMembers(chatId: ID, userIds: ID[]): Promise<FailedInvitation[]>;
    openChat(chatId: ID, params?: OpenChatParams): Promise<void>;
    closeChat(chatId: ID): Promise<void>;
    createGroup(title: string, params?: CreateGroupParams): Promise<ChatPGroup>;
    createSupergroup(title: string, params?: CreateSupergroupParams): Promise<ChatPSupergroup>;
    createChannel(title: string, params?: CreateChannelParams): Promise<ChatPChannel>;
    setMessageTtl(chatId: ID, messageTtl: number): Promise<void>;
    archiveChats(chatIds: ID[]): Promise<void>;
    archiveChat(chatId: ID): Promise<void>;
    unarchiveChats(chatIds: ID[]): Promise<void>;
    unarchiveChat(chatId: ID): Promise<void>;
    getCommonChats(userId: ID, params?: GetCommonChatsParams): Promise<ChatP[]>;
    getChatSettings(chatId: ID): Promise<ChatSettings>;
    disableBusinessBots(chatId: ID): Promise<void>;
    enableBusinessBots(chatId: ID): Promise<void>;
    disableSlowMode(chatId: ID): Promise<void>;
    setSlowMode(chatId: ID, duration: SlowModeDuration): Promise<void>;
    setChatTitle(chatId: ID, title: string): Promise<void>;
    setChatDescription(chatId: ID, description: string): Promise<void>;
    setMemberListVisibility(chatId: ID, visible: boolean): Promise<void>;
    setTopicsEnabled(chatId: ID, enabled: boolean, tabs: boolean): Promise<void>;
    setAntispamEnabled(chatId: ID, enabled: boolean): Promise<void>;
    setSignaturesEnabled(chatId: ID, enabled: boolean, params?: SetSignaturesEnabledParams): Promise<void>;
    deleteChat(chatId: ID): Promise<void>;
    getDiscussionChatSuggestions(): Promise<ChatP[]>;
    setDiscussionChat(chatId: ID, discussionChatId: ID): Promise<void>;
    transferChatOwnership(chatId: ID, userId: ID, password: string): Promise<void>;
    createTopic(chatId: ID, title: string, params?: CreateTopicParams): Promise<Topic>;
    editTopic(chatId: ID, topicId: number, title: string, params?: EditTopicParams): Promise<Topic>;
    hideGeneralTopic(chatId: ID): Promise<void>;
    showGeneralTopic(chatId: ID): Promise<void>;
    closeTopic(chatId: ID, topicId: number): Promise<void>;
    reopenTopic(chatId: ID, topicId: number): Promise<void>;
    pinTopic(chatId: ID, topicId: number): Promise<void>;
    unpinTopic(chatId: ID, topicId: number): Promise<void>;
    promoteChatMember(chatId: ID, userId: ID, params?: PromoteChatMemberParams): Promise<void>;
    sendCallbackQuery(botId: ID, messageId: number, question: CallbackQueryQuestion): Promise<CallbackQueryAnswer>;
    answerCallbackQuery(id: string, params?: AnswerCallbackQueryParams): Promise<void>;
    sendInlineQuery(botId: ID, chatId: ID, params?: SendInlineQueryParams): Promise<InlineQueryAnswer>;
    answerInlineQuery(id: string, results: InlineQueryResult[], params?: AnswerInlineQueryParams): Promise<void>;
    setMyDescription(params?: {
        description?: string;
        languageCode?: string;
    }): Promise<void>;
    setMyName(params?: {
        name?: string;
        languageCode?: string;
    }): Promise<void>;
    setMyShortDescription(params?: {
        shortDescription?: string;
        languageCode?: string;
    }): Promise<void>;
    getMyDescription(params?: {
        languageCode?: string;
    }): Promise<string>;
    getMyName(params?: {
        languageCode?: string;
    }): Promise<string>;
    getMyShortDescription(params?: {
        languageCode?: string;
    }): Promise<string>;
    setMyCommands(commands: BotCommand[], params?: SetMyCommandsParams): Promise<void>;
    getMyCommands(params?: GetMyCommandsParams): Promise<BotCommand[]>;
    setReactions(chatId: ID, messageId: number, reactions: Reaction[], params?: SetReactionsParams): Promise<void>;
    addReaction(chatId: ID, messageId: number, reaction: Reaction, params?: AddReactionParams): Promise<void>;
    removeReaction(chatId: ID, messageId: number, reaction: Reaction): Promise<void>;
    createStory(chatId: ID, content: InputStoryContent, params?: CreateStoryParams): Promise<Story>;
    getStories(chatId: ID, storyIds: number[]): Promise<Story[]>;
    getStory(chatId: ID, storyId: number): Promise<Story | null>;
    deleteStories(chatId: ID, storyIds: number[]): Promise<void>;
    deleteStory(chatId: ID, storyId: number): Promise<void>;
    addStoriesToHighlights(chatId: ID, storyIds: number[]): Promise<void>;
    addStoryToHighlights(chatId: ID, storyId: number): Promise<void>;
    removeStoriesFromHighlights(chatId: ID, storyIds: number[]): Promise<void>;
    removeStoryFromHighlights(chatId: ID, storyId: number): Promise<void>;
    getNetworkStatistics(): Promise<NetworkStatistics>;
    blockUser(userId: ID): Promise<void>;
    unblockUser(userId: ID): Promise<void>;
    startVideoChat(chatId: ID, params?: StartVideoChatParams): Promise<VideoChatActive>;
    scheduleVideoChat(chatId: ID, startAt: number, params?: ScheduleVideoChatParams): Promise<VideoChatScheduled>;
    joinVideoChat(id: string, params_: string, params?: JoinVideoChatParams): Promise<string>;
    leaveVideoChat(id: string): Promise<void>;
    joinLiveStream(id: string): Promise<void>;
    getVideoChat(id: string): Promise<VideoChat>;
    getLiveStreamChannels(id: string): Promise<LiveStreamChannel[]>;
    downloadLiveStreamSegment(id: string, channelId: number, scale: number, timestamp: number, params?: DownloadLiveStreamSegmentParams): Promise<Uint8Array>;
    answerPreCheckoutQuery(preCheckoutQueryId: string, ok: boolean, params?: AnswerPreCheckoutQueryParams): Promise<void>;
    refundStarPayment(userId: ID, telegramPaymentChargeId: string): Promise<void>;
    getContacts(): Promise<User[]>;
    deleteContacts(userIds: ID[]): Promise<void>;
    deleteContact(userId: ID): Promise<void>;
    addContact(userId: ID, params?: AddContactParams): Promise<void>;
    getTranslations(params?: GetTranslationsParams): Promise<Translation[]>;
    getGifts(): Promise<Gift[]>;
    getClaimedGifts(chatId: ID, params?: GetClaimedGiftsParams): Promise<ClaimedGifts>;
    sendGift(chatId: ID, giftId: string, params?: SendGiftParams): Promise<void>;
    sellGift(userId: ID, messageId: number): Promise<void>;
    getGift(slug: string): Promise<Gift>;
}
//# sourceMappingURL=5_client_dispatcher.d.ts.map